version: "3.7"
services:
  noise-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.noise 
    entrypoint: /usr/local/bin/entrypoint.sh
    command:
      - noisepage
      - serve
    container_name: noise-dev
    restart: always
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - "/Users/anglenet/playground/workspace/cpp/noisepage:/home/master/noise"
    cap_add:
      - SYS_PTRACE #fix gdb issue
