version: "3.7"
services:
  oceanbase-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.oceanbase
    entrypoint: /usr/local/bin/entrypoint.sh
    command:
      - base
      - serve
    container_name: oceanbase-dev
    restart: always
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - "/Users/anglenet/playground/wip/oceanbase:/home/master/oceanbase"
    cap_add:
      - SYS_PTRACE #fix gdb issue
