version: "3.7"
services:
  ydb-dev:
    build: ./
    entrypoint: /usr/local/bin/entrypoint.sh
    command:
      - ydb
      - serve
    container_name: ydb-dev
    restart: always
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - "/Users/anglenet/playground/workspace/cpp/ydb:/home/master/ydb"
    cap_add:
      - SYS_PTRACE #fix gdb issue
